### ISSUE TITLE
api.js - ModelArray not found

### ISSUE THREAD

**Issue by justinobney** [keithwhor/nodal#134]
https://github.com/keithwhor/nodal/blob/master/core%2Frequired%2Fapi.js#L17

```
2016-01-24T06:00:05.077664+00:00 app[web.1]: ReferenceError: ModelArray is not defined
2016-01-24T06:00:05.077666+00:00 app[web.1]:     at APIConstructor.format (/app/node_modules/nodal/core/required/api.js:17:30)
2016-01-24T06:00:05.077668+00:00 app[web.1]:     at V1AppProfilesController.respond (/app/node_modules/nodal/core/required/controller.js:272:23)
2016-01-24T06:00:05.077669+00:00 app[web.1]:     at /app/app/controllers/v1/app_profiles_controller.js:43:22
2016-01-24T06:00:05.077670+00:00 app[web.1]:     at /app/node_modules/nodal/core/required/model.js:1020:9
2016-01-24T06:00:05.077671+00:00 app[web.1]:     at /app/node_modules/nodal/node_modules/async/lib/async.js:726:13
2016-01-24T06:00:05.077671+00:00 app[web.1]:     at /app/node_modules/nodal/node_modules/async/lib/async.js:52:16
2016-01-24T06:00:05.077672+00:00 app[web.1]:     at /app/node_modules/nodal/node_modules/async/lib/async.js:269:32
2016-01-24T06:00:05.077673+00:00 app[web.1]:     at /app/node_modules/nodal/node_modules/async/lib/async.js:44:16
2016-01-24T06:00:05.077674+00:00 app[web.1]:     at /app/node_modules/nodal/node_modules/async/lib/async.js:723:17
2016-01-24T06:00:05.077681+00:00 app[web.1]:     at /app/node_modules/nodal/node_modules/async/lib/async.js:167:37
```

**Comment by keithwhor** [comment]
Fixing.

**Comment by keithwhor** [comment]
Fixed, tests added. (Was at Star Wars or would've fixed sooner. :) Thanks for the catch! :+1:)

https://github.com/keithwhor/nodal/commit/3b8623d6e8b28204240fd2700ec29aa6bba34ba2

**Comment by justinobney** [comment]
It's what I get for pointing my package.json at github instead of NPM 😜
