### ISSUE TITLE
GzipMiddleware bug causes default app to fail.

### ISSUE THREAD

**Issue by paulhart** [keithwhor/nodal#136]
GzipMiddleware is currently causing the default application to fail. tl;dr version: **TypeError: callback is not a function at GzipMiddleware.exec (/Users/paulhart/Projects/replicate-bug/middleware/gzip_middleware.js:58:7)**

```
Phoenix:Projects paulhart$ nodal new replicate-bug

Welcome to Nodal!

Let's get some information about your project...

name (my-nodal-project) replicate-bug
author (mysterious author) Paul Hart

Creating directory "replicate-bug"...

Copying Nodal directory structure and files...

Installing packages in this directory...

replicate-bug@0.0.0 /Users/paulhart/Projects/replicate-bug
└─┬ nodal@0.5.8-rc3 
  ├─┬ any-db@2.1.0 
  │ ├── any-db-pool@2.0.1 
  │ └── parse-db-url@0.0.0 
  ├─┬ any-db-pool@2.1.0 
  │ ├── generic-pool@2.0.4 
  │ └── once@1.1.1 
  ├─┬ any-db-postgres@2.1.4 
  │ ├── inherits@2.0.1 
  │ └── pg-query-stream@0.2.0 
  ├─┬ any-db-transaction@2.2.2 
  │ ├─┬ once@1.3.3 
  │ │ └── wrappy@1.0.1 
  │ └── yafsm@0.0.0 
  ├── async@1.5.2 
  ├── colors@1.1.2 
  ├─┬ cross-spawn-async@2.1.6 
  │ ├─┬ lru-cache@4.0.0 
  │ │ ├── pseudomap@1.0.2 
  │ │ └── yallist@2.0.0 
  │ └─┬ which@1.2.2 
  │   ├─┬ is-absolute@0.1.7 
  │   │ └── is-relative@0.1.3 
  │   └── isexe@1.0.1 
  ├── deep-equal@1.0.1 
  ├── dot@1.0.3 
  ├─┬ fs-extra@0.26.4 
  │ ├── graceful-fs@4.1.2 
  │ ├── jsonfile@2.2.3 
  │ ├── klaw@1.1.3 
  │ ├── path-is-absolute@1.0.0 
  │ └─┬ rimraf@2.5.1 
  │   └─┬ glob@6.0.4 
  │     ├─┬ inflight@1.0.4 
  │     │ └── once@1.3.3 
  │     ├─┬ minimatch@3.0.0 
  │     │ └─┬ brace-expansion@1.1.2 
  │     │   ├── balanced-match@0.3.0 
  │     │   └── concat-map@0.0.1 
  │     └── once@1.3.3 
  ├─┬ http-proxy@1.12.0 
  │ ├── eventemitter3@1.1.1 
  │ └── requires-port@0.0.1 
  ├── i@0.3.4 
  ├─┬ inquirer@0.11.3 
  │ ├── ansi-escapes@1.1.1 
  │ ├── ansi-regex@2.0.0 
  │ ├─┬ chalk@1.1.1 
  │ │ ├── ansi-styles@2.1.0 
  │ │ ├── escape-string-regexp@1.0.4 
  │ │ ├── has-ansi@2.0.0 
  │ │ └── supports-color@2.0.0 
  │ ├─┬ cli-cursor@1.0.2 
  │ │ └─┬ restore-cursor@1.0.1 
  │ │   ├── exit-hook@1.1.1 
  │ │   └── onetime@1.1.0 
  │ ├── cli-width@1.1.0 
  │ ├── figures@1.4.0 
  │ ├── lodash@3.10.1 
  │ ├─┬ readline2@1.0.1 
  │ │ ├─┬ code-point-at@1.0.0 
  │ │ │ └── number-is-nan@1.0.0 
  │ │ ├── is-fullwidth-code-point@1.0.0 
  │ │ └── mute-stream@0.0.5 
  │ ├─┬ run-async@0.1.0 
  │ │ └── once@1.3.3 
  │ ├── rx-lite@3.1.2 
  │ ├── string-width@1.0.1 
  │ ├── strip-ansi@3.0.0 
  │ └── through@2.3.8 
  ├─┬ mime-types@2.1.9 
  │ └── mime-db@1.21.0 
  ├── mocks@0.0.15 
  └─┬ pg@4.4.3 
    ├── buffer-writer@1.0.0 
    ├── generic-pool@2.1.1 
    ├── packet-reader@0.2.0 
    ├── pg-connection-string@0.1.3 
    ├─┬ pg-types@1.10.0 
    │ ├── ap@0.2.0 
    │ ├── postgres-array@1.0.0 
    │ ├── postgres-bytea@1.0.0 
    │ ├── postgres-date@1.0.1 
    │ └─┬ postgres-interval@1.0.1 
    │   └── xtend@4.0.1 
    ├─┬ pgpass@0.0.3 
    │ └── split@0.3.3 
    └── semver@4.3.6 


All done!

Your new Nodal project, replicate-bug, is ready to go! :)

Have fun Paul Hart, and check out https://github.com/keithwhor/nodal for the most up-to-date Nodal information

Pro tip: You can try running your server right away with:

  cd replicate-bug && nodal s

Phoenix:Projects paulhart$ cd replicate-bug && nodal s

> replicate-bug@0.0.0 start /Users/paulhart/Projects/replicate-bug
> node server.js --harmony_classes

Nodal HTTP server listening on port 3000
* Request aborted: /
TypeError: callback is not a function
    at GzipMiddleware.exec (/Users/paulhart/Projects/replicate-bug/middleware/gzip_middleware.js:58:7)
    at /Users/paulhart/Projects/replicate-bug/node_modules/nodal/core/required/execution_queue.js:57:23
    at fn (/Users/paulhart/Projects/replicate-bug/node_modules/async/lib/async.js:746:34)
    at /Users/paulhart/Projects/replicate-bug/node_modules/async/lib/async.js:1213:16
    at /Users/paulhart/Projects/replicate-bug/node_modules/async/lib/async.js:166:37
    at /Users/paulhart/Projects/replicate-bug/node_modules/async/lib/async.js:706:43
    at /Users/paulhart/Projects/replicate-bug/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/Users/paulhart/Projects/replicate-bug/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
^C
Phoenix:replicate-bug paulhart$ node --version
v5.5.0
Phoenix:replicate-bug paulhart$ 
```

**Comment by intabulas** [comment]
@paulhart the issue would be that middleware and renderware have different api surfaces for `exec()`. A renderware has a additional data arg. Whats confusing me is that gzip was converted to renderware before 0.5.7 and I see nodal@0.5.8-rc3 in your issue above.

can you `cat <appdir>/node_modules/nodal/package.json` so I can see the nodal version in the app

I just tested a new app running bother based off master and one based on a clean nodal (0.5.8-rc3) from npm both generate the gzip renderware vs old gzip middlware

**Comment by keithwhor** [comment]
Run `npm update nodal -g` to update your CLI tools. They're outdated. Should fix. LMK.

**Comment by paulhart** [comment]
Keith, agreed, it's resolved. I had to manually delete my /usr/local/lib/node_modules/nodal directory and reinstall to get it to work correctly; update was encountering an error and exiting.
