### ISSUE TITLE
@keithwhor Vague error message if user forgets to migrate data

### ISSUE THREAD

**Issue by jacoblee93** [keithwhor/nodal#188]
Error below:

Application Error

TypeError: Cannot read property 'table' of undefined
    at Function.table (/Users/jacoblee/Desktop/echostream/node_modules/nodal/core/required/model.js:139:35)
    at Function.setSchema (/Users/jacoblee/Desktop/echostream/node_modules/nodal/core/required/model.js:269:36)
    at /Users/jacoblee/Desktop/echostream/app/models/collaboration.js:10:17
    at Object.<anonymous> (/Users/jacoblee/Desktop/echostream/app/models/collaboration.js:17:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

**Comment by keithwhor** [comment]
:+1: Thanks! Will get on this.
