### ISSUE TITLE
Running Nodal from CLI

### ISSUE THREAD

**Issue by xeoneux** [keithwhor/nodal#237]
Running Nodal without any arguments returns this error:

```js
/usr/local/lib/node_modules/nodal/node_modules/cmnd/lib/command_line_interface.js:22
      commands = commands.split(':');
                         ^

TypeError: Cannot read property 'split' of undefined
    at CommandLineInterface.parse (/usr/local/lib/node_modules/nodal/node_modules/cmnd/lib/command_line_interface.js:22:26)
    at CommandLineInterface.run (/usr/local/lib/node_modules/nodal/node_modules/cmnd/lib/command_line_interface.js:133:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodal/cli/bin.js:6:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
```

**Comment by keithwhor** [comment]
Nice catch. Thanks! This error is actually is in https://github.com/keithwhor/cmnd

I'll open an issue there :)

**Comment by keithwhor** [comment]
https://github.com/keithwhor/cmnd/issues/3
