### ISSUE TITLE
nodal g:controller not working

### ISSUE THREAD

**Issue by jeroenransijn** [keithwhor/nodal#288]
I am getting this error:

```
/usr/local/lib/node_modules/nodal/cli/commands/g/controller.js:134
    if (Object.keys(vflags).filter(key => key.substr(0, 4) === 'for:').length) {
                    ^

ReferenceError: vflags is not defined
    at GenerateControllerCommand.run (/usr/local/lib/node_modules/nodal/cli/commands/g/controller.js:134:21)
    at CommandLineInterface.run (/usr/local/lib/node_modules/nodal/node_modules/cmnd/lib/command_line_interface.js:191:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodal/cli/bin.js:6:5)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

I think it should be `params.vflags` from glancing over it. Didn't check it all too much though.

```javascript
if (Object.keys(params.vflags).filter(key => key.substr(0, 4) === 'for:').length) {
      return callback(new Error('Syntax `--for:ModelName` removed. Use `--for ModelName` instead.'));
    }
```

**Comment by jeroenransijn** [comment]
Just changed this in `/usr/local/lib/node_modules/nodal/cli/commands/g/` and can confirm it's working.

**Comment by Rcomian** [comment]
I just hit this too and can confirm the fix.

**Comment by russjohnson** [comment]
Thanks for posting this. I can confirm the issue/fix. Been beating my head for half an hour...

**Comment by keithwhor** [comment]
Fixed in https://github.com/keithwhor/nodal/commit/57e3b3a080b20a0247fa9027a725fece29afc69f

Thanks for the catch!
