### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by rcrooks** [keithwhor/nodal#42]
Following the instructions in the readme, but getting this when I try to install nodal:

module.js:328
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by keithwhor** [comment]
What Node version are you running? I encountered this doing debugging as a Node 5.x issue. It has to do with a problem with the OS X installer. Try using Node 4.2.4 instead.

See:
https://github.com/npm/npm/issues/10449,
https://github.com/npm/npm/issues/10434

**Comment by keithwhor** [comment]
I'm going to close this for now. If your issue persists, feel free to comment again and I'll reopen it. :)

**Comment by rcrooks** [comment]
Ok - I am on 5.4 I'll try downgrading.
Thanks.
On Thu, Jan 7, 2016 at 13:01 Keith Horwood <notifications@github.com> wrote:

> Closed #42 <https://github.com/keithwhor/nodal/issues/42>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keithwhor/nodal/issues/42#event-508541930>.
>
-- 
Robert Crooks
Director of Learning Services
Brightcove, Inc
