### ISSUE TITLE
Syntax error when calling 'nodal new'

### ISSUE THREAD

**Issue by bretth18** [keithwhor/nodal#77]
installed a fresh nodal build, ran into this error when creating a new project

```
/usr/local/lib/node_modules/nodal/cli/cli.js:7
  const colors = require('colors/safe');
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

**Comment by schahriar** [comment]
What version of NodeJS are you using?

**Comment by bretth18** [comment]
0.12.2, will try with another version

**Comment by schahriar** [comment]
It should work in 4.x and above.

**Comment by bretth18** [comment]
works on  node v4.2.4, confirmed to not work on 0.12.2

**Comment by schahriar** [comment]
@bretth18 sounds about right. Nodal supports v4.x and above used for ES6 features.
